[build]
  base = "/"
  publish = "www"
  command = "ionic build --prod"
  functions = ".lambda"
[[redirects]]
  from = "/.netlify/*"
  status = 200
  to = "/.netlify/:splat"
[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"